services:
  db:
    image: postgres:15
    container_name: mwp-ci-db
    environment:
      POSTGRES_DB: postgres # banco default, NÃO moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
    ports:
      - "54321:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  ci:
    image: moodlehq/moodle-workplace-plugin-ci:8.3
    container_name: mwp-ci-runner
    depends_on:
      - db
    working_dir: /plugin
    volumes:
      - ./:/plugin
    environment:
      MOODLE_BRANCH: MOODLE_405_STABLE
      DB: pgsql # tipo de DB (compatível com versões antigas) [web:92]
      DB_TYPE: pgsql # tipo de DB (nova forma, tem prioridade) [web:4]
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
    entrypoint: [ "bash", "-lc", "sleep infinity" ]

volumes:
  dbdata:
